# name: Samishop 4 Web CI

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     name: Deploy
#     runs-on: ubuntu-latest

#     env:
#       working-directory: ./
#       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#     strategy:
#       matrix:
#         node-version: [16.x]

#     steps:
#       - name: Checking out project
#         uses: actions/checkout@v3

#       - name: Configure AWS
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: ${{ secrets.AWS_REGION }}

#       - name: Deploy to S3
#         run: aws s3 sync --exact-timestamps ${{ secrets.SOURCE_DIR }} s3://${{ secrets.AWS_S3_BUCKET_PROD }}

#       - name: Deploy to Template S3
#         run: aws s3 sync --exact-timestamps ${{ secrets.SOURCE_DIR }} s3://${{ secrets.AWS_S3_BUCKET_TEMPLATE_PROD }}
